version: '3'

services:

    postgres:
        image: postgres:12.2
        ports: 
            - 5432:5432
        environment:
            POSTGRES_USER: admin_test
            POSTGRES_PASSWORD: root
            POSTGRES_DB: my_test
        volumes:
            - pg_data:/var/lib/postgresql/data

    
    application:
        build: .
        ports: 
            - 8888:8000 
        volumes: 
            - .:/code
    
        command: python manage.py runserver 0.0.0.0:8000 
        depends_on:
            - postgres 
            
volumes:
    pg_data: {}  
             
